@echo off
echo Starting Chrome with remote debugging on port 9222...
"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir="%TEMP%\chrome-devtools-mcp-profile" http://localhost:5173
